### ISSUE TITLE
new and maybe better scifi_metroid texture

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/mobs_scifi#3]
![scifi_metroid](https://cloud.githubusercontent.com/assets/16853304/20566350/09fdc234-b195-11e6-8c82-8eda3dba82f2.png)

**Comment by D00Med** [comment]
Thankyou for this! I'm not happy with the quality of the mod at the moment so I'm thinking of remaking a lot of the modes, including the metroid.

**Comment by tobyplowy** [comment]
@D00Med I think I should Focus More on Minecraft Style Keep the cubes perfect cubes and Keep the resolution of The textures low (try to Keep the pixels on the model Around The Same size of a 16 by 16 block Texture pixel in The game) your uv map should be Around 128x128 maximum but Only for Big models. keep in Mind This is My Idea of a good Quality Model

**Comment by tobyplowy** [comment]
@D00Med with otther words Keep all your models Made out of cubes only cubes but don't do this https://www.physicsforums.com/attachments/irregular-trapezoidal-cube-jpg.39977/
Keep all sides of the Cube equal in size

**Comment by D00Med** [comment]
I agree! I try to do that with my other mobs.
I want to texture the models similar to the way I did in my vehicles mod, which uses textures that are mostly 512x512.

**Comment by tobyplowy** [comment]
@D00Med yes but your vehicles are very detailed I know that Sounds weird but for a game like minetest that's a lot of detail (Again it Should Only be made out of cubes)

**Comment by tobyplowy** [comment]
@D00Med I have an example of a Xenomorph someone made for Minecraft http://i.imgur.com/6Dwzbtp.png http://i.imgur.com/JUnMXOn.png It is Only Made out of cubes and it Looks really awesome also I know this is a bit off topic XD

**Comment by D00Med** [comment]
True, I'll try to make the textures smaller. I don't like the textures to bleed over the corners though, and it is harder to avoid on a small texture. But it's fine for things like animals and monsters which wouldn't normally have 90 corners and flat surfaces. They're cool aren't they? I did have a reason for not using plain cubes for mine, but I can't remember what it was.

**Comment by tobyplowy** [comment]
@D00Med yes your Models Are amazing it's better than what I can do (i suck at modeling But i Have my Moments XD) can I have a try at making a metroide model

**Comment by tobyplowy** [comment]
@D00Med Also anotther tip trie to Limit The amount of cubes you use 
(Only use whats needed)

**Comment by D00Med** [comment]
Sure, I'd be interested to see. I want to try making a new one with a partially transparent texture, do you know if that is possible? I didn't think it was, but there are some transparent meshes in the homedecor mod. Yes I will certainly try to do that

**Comment by tobyplowy** [comment]
@D00Med I'm not a programmer I'm A "artist" I don't know What's Possible with Minetest engine but I tried a transparent texture on The model you made for the Metroid and it didn't work so I don't know, it would look a lot Better tho :)

**Comment by D00Med** [comment]
*high five* me too, well I do programming too obviously. 
Yeah it doesn't work just with the texture, I think it needs to have something changed on the model. 
I'll let you know if I succeed.

**Comment by tobyplowy** [comment]
@D00Med here I have a metroide model keep in mind that this is a test texture and also the website isn't displaying correctly https://sketchfab.com/models/4890fd970ca44faba2d52f6756a32cfe

**Comment by D00Med** [comment]
Looks good! I'm attempting to make a transparent one https://s13.postimg.org/rh24m2yon/myattempt.png

**Comment by D00Med** [comment]
It doesn't work in the game though

**Comment by tobyplowy** [comment]
@D00Med I like how you put 2 cubes inside of each other to make it look more detailed nice Idea :)

**Comment by tobyplowy** [comment]
@D00Med By the way Did You Know i Made my model with sketchup XD

**Comment by tobyplowy** [comment]
@D00Med also you forgot to add the small teeth he has four of them two big ones and 2 small ones http://vignette4.wikia.nocookie.net/metroid/images/d/d8/Metroid4_07.jpg/revision/latest/scale-to-width-down/275?cb=20100322225155

So I'm Willing to help with textures for blocks and Models If You are interested of course :D

**Comment by D00Med** [comment]
I saw some of your other models, they are very nice.
Yes you are right, I think the mod needs a hybrid between your model and mine. 
On the subject of models, yesterday I tried making a better quality model: https://s14.postimg.org/ne30qho0x/fdfd.png
Based on this:
http://2.bp.blogspot.com/-G1dEacfk6nM/T2LWuYnejkI/AAAAAAACLv8/xQW5MRhpMLc/s1600/1.jpg
I used only blocks like you suggested(apart from the shields on the shoulders), but the texture is 512x512. It has taken me 8 hours to make, and I still have to finish texturing it O_O
Do you think it is worth the effort?
Help would be very much appreciated, but I'd prefer it if you used the same software as me so that I can make adjustments, can you use blender?

**Comment by tobyplowy** [comment]
@D00Med pardon My language but your model is fucking AWESOME it's perfect it was definitely Worth Every second minute and hour (in case You didn't understand that It's a really high quality model Nice work!)

also I just used blender for the first time I'm still learning it but I can make a model out of cubes but That's All I can do, I cannot uv unwrap and I can just make cubes and scale them XD

**Comment by tobyplowy** [comment]
@D00Med I Made this facehugger model with all the skill i have in blender (as you can see it's not much) https://1drv.ms/u/s!Ammw1yWbBi3R4B4Zo_onWuSYO-Da 
Problems about the thing I made the model is not 100% symmetrical and I just copy-pasted everything 
but maybe it's useful to you in some way

**Comment by tobyplowy** [comment]
@D00Med if you are interested in using the facehugger model you can use it for whatever you want as long as you give me credit for it of course :) also I would recommend the texture map to be 32x32 pixels (it's a very small model so it doesn't need a Lot of detail)

**Comment by D00Med** [comment]
That model looks really really nice! I will definitely use it in the mod

**Comment by tobyplowy** [comment]
@D00Med is your robot finished I Can't wait to see How It Looks whin its done

**Comment by tobyplowy** [comment]
@D00Med I made a new model this time it's a gun I just did it for the fun of it to test my skill  maybe you can use it https://1drv.ms/u/s!Ammw1yWbBi3R4CHvQ_2lz2E-XxWu 

also shuld i Keep making Models like this or are These not useful to you?

**Comment by D00Med** [comment]
Nice model! They are useful, but I suggest you only make models that you would want to use even if I didn't. It'd be a shame if you made one and I (really) didn't want to put it in my mod.
Yep it's finished, not as a mob yet, but as a vehicle: https://github.com/D00Med/vehicles/tree/assault-suit

**Comment by tobyplowy** [comment]
@D00Med do you have any models I should make?

**Comment by D00Med** [comment]
:] hmmm nothing comes to mind. Do you think you could do a better version of the "Iron Giant" model?

**Comment by tobyplowy** [comment]
@D00Med I can try, keep in mind I cannot Texture it i cant add bones

**Comment by D00Med** [comment]
That's no problem, I can do both

**Comment by tobyplowy** [comment]
@D00Med again off topic but I think If the sci-fi node Builder was a 3D printer that Would Be amazing :)

**Comment by tobyplowy** [comment]
@D00Med also of topic another thing I Wanted to ask are you still working on the The Legend Of minetest

**Comment by D00Med** [comment]
Yes that'd be really really cool!
Not really, but there seems to be interest in it lately so I might update it a bit.
I'm trying to concentrate my efforts on finishing my mods for now.

**Comment by tobyplowy** [comment]
@D00Med if you do continue the loz mod can I help with it also I think there's a couple of mods that don't really fit the game :/

**Comment by D00Med** [comment]
Ok, which ones do you think are out of place?

**Comment by tobyplowy** [comment]
@D00Med to be Clear im talking about the legend of minetest mod
These are the mods I think You're out of Place
Farming+
The bace content from mobs redo
X-decor (a bit straige But i can understand Why you Did It)

Also Another problem is the textures they are not consistent 
Some are 32x32 others are 16x16 

And Maybe If You are Willing to do that make the mobs out of cubes (you know what i Mean I've explained it a couple times already) if you can get the same quality as you did with your robot model well that would be insane But also Nice XD

keep in mind I really appreciate your work You're awesome and Maybe You're one of the best minetest moders Out there But sush I don't want to start a war

**Comment by D00Med** [comment]
Ok. 
Farming_redo is in there for something else to do, and personally I think the standard farming mod is a bit boring. Fair enough about mobs_redo.
Yes the textures are a bit of a problem. 
That's a good idea! Actually, the mobs in that game are the first I ever made, so they could definitely benefit from being re-made. Haha thanks :D

**Comment by tobyplowy** [comment]
@D00Med again I'm willing to help with models and textures for lomt (the legend of minetest)
Because I haven't said it enuf XD

( what is the game aiming for is it all loz games or Only a couple)

**Comment by D00Med** [comment]
Well it'd be great if you could do a model of this http://vignette2.wikia.nocookie.net/zelda/images/2/27/Stallord.png/revision/latest?cb=20100107003651
It's meant to be a bit of a mixture, and something else entirely.

**Comment by tobyplowy** [comment]
I'm not sure If my skill allows me To do that But a Challenge Is Always fun (also This If from Twilight princess isent it Will midna de added too (she's my favorite character from the game)

**Comment by tobyplowy** [comment]
@D00Med also a small thing Will you put The download on GitHub instead of that website

**Comment by D00Med** [comment]
Ok then, yeah have fun. That's a good idea!
Yes definitely, I've been meaning to do so for a while.

**Comment by tobyplowy** [comment]
@D00Med I tried making that model but it's pretty much impossible I don't have the skill for it i just spend 3 hours trying to do it sorry dat i cant do it :/

**Comment by D00Med** [comment]
Ah ok, well thanks for trying. 
I noticed something strange about your facehugger model. I joined all the cubes into one object(a requirement for animating it), but afterwards I noticed it still has a separate material and texture for every cube on the model. How did you do this? It's not good because it makes the blender file messy. But it can be fixed.

**Comment by tobyplowy** [comment]
@D00Med I just copy-pasted the standard Cube that's there when you start the program and i scaled and stretched it

**Comment by tobyplowy** [comment]
@D00Med can i make a midna model?

**Comment by D00Med** [comment]
O.o that's a bit odd then. 
Sure, but this time, can you use the "create" button in the tools tab instead of copying the base cube?

**Comment by D00Med** [comment]
O.o that's a bit odd then. 
Sure, but this time, can you use the "create" button in the tools tab instead of copying the base cube?

**Comment by tobyplowy** [comment]
@D00Med Can I copy pacte the Cube that is Made From The add menu?

**Comment by D00Med** [comment]
Yes I think so

**Comment by tobyplowy** [comment]
@D00Med body is Done now face

**Comment by D00Med** [comment]
cool :) I'm texturing the facehugger at the moment

**Comment by tobyplowy** [comment]
@D00Med Yay team work XD

**Comment by D00Med** [comment]
xD I'm interested to see what your model of Midna looks like.
It will be interesting to texture

**Comment by tobyplowy** [comment]
@D00Med I'm having trouble with the helmet :/

**Comment by D00Med** [comment]
See what you can do with it, I might be able to improve it after.
How's this texture?
https://s17.postimg.org/pmnmrf3jj/hugs.png

**Comment by tobyplowy** [comment]
The bottom should be a bit more Red pink colored to indicate his mouth https://www.google.be/search?q=facehugger&client=tablet-android-google&prmd=ivsn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiHp_2MqcXQAhXCvBoKHUqWB_MQ_AUIBygB#imgrc=K4pS3h5VJmRAZM%3A

Also Nice work

**Comment by tobyplowy** [comment]
@D00Med im almost Done with my model

**Comment by tobyplowy** [comment]
@D00Med Done 

https://1drv.ms/u/s!Ammw1yWbBi3R4CMWk24rn1I6Rg2O

**Comment by D00Med** [comment]
Nice! The helmet looks good.
Just one thing, which I've fixed, the flat planes can only be viewed from 1 side, so in future you should make another, with flipped normals, just beside each plane.

**Comment by tobyplowy** [comment]
@D00Med those are supposed to be her ears thats going to need some texture Magic (the ears need to be a picture instead of a cube because I'm planning to make a HD texture version of it, for practice

**Comment by tobyplowy** [comment]
@D00Med also there's a cube on top of her head in between those small cubes and the Big Horns or whatever they are that's supposed to represent her hair (it needs to be orange)

**Comment by D00Med** [comment]
Yeah, ok then.
I'll have a go at texturing it too, and we can see whose is better :'D

**Comment by tobyplowy** [comment]
@D00Med what are we talking about midna or facugger also Mean XD

**Comment by D00Med** [comment]
Midna. haha

**Comment by tobyplowy** [comment]
@D00Med is the midna model good?

**Comment by D00Med** [comment]
yes! definitely, it's impressive

**Comment by tobyplowy** [comment]
@D00Med Also im gonna Sleep its 3:24 Midnight see you tomorrow and hey if you have any more models you need just say the word also I really enjoy working together (and I have another idea for a (lomt) model http://zeldawiki.org/images/thumb/8/83/ST_Phantom.png/260px-ST_Phantom.png

**Comment by D00Med** [comment]
Ok then, talk tomorrow.
Yeah, it's a pleasure.
That's cool

**Comment by tobyplowy** [comment]
@D00Med this is how the texture shuld look like
![midna](https://cloud.githubusercontent.com/assets/16853304/20640626/9732f58e-b3e3-11e6-8c34-210da635a3ac.png)

bdw i made this with gimp it took me for ever :D

**Comment by tobyplowy** [comment]
@D00Med also you will have to Lower the Helmet down a little bit so it matches the picture ( I put the helmet way too high in the file i gave you

**Comment by tobyplowy** [comment]
@D00Med added more detail on the helmet 
![midna](https://cloud.githubusercontent.com/assets/16853304/20641229/e4f4a550-b3f3-11e6-8864-cdd938c9a74a.png)

**Comment by D00Med** [comment]
That looks really good. Is the shading in the texture? 
It takes a while in gimp doesn't it? I use gfie, and I spend most of the time working out which face is which on the texture.

**Comment by D00Med** [comment]
Oh by the way, the front of models should be parrallel to the "y" axis for use in minetest.
That green line in little diagram in the corner of blender should point the same direction as the model

**Comment by tobyplowy** [comment]
@D00Med you miss understood that, the Texture is a Photoshop to look like it has a Texture 
(i took a screenshot of the model and Just Photoshoped It with gimp) in reality It Doesn't have a Texture It's just a Photoshop

**Comment by D00Med** [comment]
Oh ok, that must have been REALLY hard then :'D
ok then, well I'll try and make the texture look something like that.
Maybe with a higher resolution though, since the game is mostly 32x32 textures.

**Comment by tobyplowy** [comment]
@D00Med I think you should use the same Dimensions that are used by Sam/steve I think it was 32 pixels tall and 64 long? (also i think the game shuld use 16 bij 16 textures they're easier to make and look better in my opinion)

**Comment by tobyplowy** [comment]
@D00Med also on the picture I made I really did my best to get the perspective right i guss it worked becuse You Fell for it :D

**Comment by D00Med** [comment]
Haha I do think 16x16 textures are nice, but I've spent waaaay too much time on that games textures to change them now. But yest that would be good. 
Yes definitely!

**Comment by tobyplowy** [comment]
@D00Med if you want you can use my Vanilla 32x32 Pack https://forum.minetest.net/viewtopic.php?f=4&t=15758

**Comment by tobyplowy** [comment]
@D00Med is it Possible to make the square particles float Around her like in This picture http://orig09.deviantart.net/5e74/f/2015/280/3/8/midna_3_color_by_chelostracks-
Oh wait wrong picture
http://img14.deviantart.net/34cb/i/2014/198/6/8/midna_by_ekaki_no_yami-d7r5nwh.jpg

Sorry about that joke i cuddent resist :P

**Comment by tobyplowy** [comment]
@D00Med there was supposed to be an awkward picture there but the link doesn't work anymore fuuuuuuuu

**Comment by D00Med** [comment]
Nice texture pack, but no thanks. I'm definitely not changing the textures of the game.
Yes the square particles are definitely possible!, I could even make them limited to when the crystal is used.
ah ok haha, looks like there's a bit missing from the link...link doesn't want anyone to see it.

**Comment by D00Med** [comment]
oh I don't know how to make the uv map change size properly, I tried changing the texture size, but it got stretched

**Comment by tobyplowy** [comment]
@D00Med  link...link doesn't want anyone to see it. 

Lol Nice pun!

**Comment by D00Med** [comment]
xD
I added that orange hand thing in Midna's head. It stretches so that it is hidden most of the time

**Comment by tobyplowy** [comment]
@D00Med also is it Possible to make dungions generate Like This one https://www.google.be/search?q=the+legend+of+zelda+dungeon&client=tablet-android-google&prmd=ivn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiN34Gio8fQAhXC1BoKHT8xDAcQ_AUIBygB#imgrc=B3Kqu1J0nB5ioM%3A

**Comment by tobyplowy** [comment]
@D00Med it shouldn't be hidden if her hand is away she Still has the hair look at This http://vignette4.wikia.nocookie.net/wii/images/6/65/Midna.jpg/revision/latest?cb=20070516022159

**Comment by D00Med** [comment]
Yes, the orange bit you made still shows up. oh ok, I see what you mean.
hmm I don't know, I tried loading a castle as a schematic but I don't think minetest likes big schematics.
And I don't understand mapgen enough to do it any other way. I could change the material used in dungeons though

**Comment by tobyplowy** [comment]
@D00Med If you can change the material in Dungeons To be those Blue bricks that Would Be A Cool reference to the older games :) also I think you shuld put the legend of minetest (tlomt) 
On github so we can continue Our Conversation there because this is really off topic unless you don't mind

**Comment by D00Med** [comment]
Ok then, sure

**Comment by D00Med** [comment]
https://github.com/D00Med/LegendofMinetest/issues/1
